name: Fetch CSV Data
on:
  push:
    branches:
      - main
    paths-ignore:
      - 'README.md'
      - 'docs/**'

defaults:
  run:
    shell: bash

jobs:
  getCsvs:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.PAT }}
      
      - name: Get Derby History
        run: |
          curl -o ./docs/_data/DerbyHistory.csv -L "https://docs.google.com/spreadsheets/d/${GSHEET_ID}/gviz/tq?tqx=out:csv&sheet=ETL-derbyHistory"
          cat ./docs/_data/DerbyHistory.csv
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}

      - name: Get Neighborhood Stats
        run: |
          curl -o ./docs/_data/neighborhoodStats.csv -L "https://docs.google.com/spreadsheets/d/${GSHEET_ID}/gviz/tq?tqx=out:csv&sheet=ETL-neighborhoodStats"
          cat ./docs/_data/neighborhoodStats.csv
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}

      - name: Get Member Stats (Summary)
        run: |
          curl -o ./docs/_data/memberStats.csv -L "https://docs.google.com/spreadsheets/d/${GSHEET_ID}/gviz/tq?tqx=out:csv&sheet=Neighbors"
          cat ./docs/_data/memberStats.csv
        env:
          GSHEET_ID: ${{ secrets.GSHEET_ID }}

      - name: Git Add and Commit
        uses: EndBug/add-and-commit@v9.0.0
        with:
          add: 'docs/_data/.'
          author_name: 'curl-pull'
          author_email: '15102e70ac374f608ee257ff035ca616@mailinator.com'
