name: Build and Deploy gh-pages
on:
  push:
    branches:
      - main
    paths:
      - 'docs/**' 

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      deployments: write
      pages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2       # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          target_path: /
          jekyll_src: docs/
          gem_src: docs/
          keep_history: true
        env:
          PAGES_REPO_NWO: ${{ github.repository }}

      - uses: sarisia/actions-status-discord@v1
        with: 
          webhook: ${{ secrets.AM_GENERAL_CHAT }}
          title: Website updated!
          description: | 
            Github Action to update AzureMeadows' website has completed.
            [Visit Website](https://azuremeadows.github.io)
