name: Build and Deploy gh-pages for branches
on:
  push:
    branches-ignore:
      - main
    # paths:
    #   - 'docs/**' 
    #   - 'garbage.txt'

defaults:
  run:
    shell: bash

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      content: write
      deployments: write
      pages: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - uses: actions/cache@v3
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - uses: helaili/jekyll-action@v2       # Choose any one of the Jekyll Actions
        with:                                # Some relative inputs of your action
          token: ${{ secrets.GITHUB_TOKEN }}
          target_branch: gh-pages
          target_path: /dev-${{ github.ref_name }}
          jekyll_src: docs/
          gem_src: docs/
        env:
          PAGES_REPO_NWO: ${{ github.repository }}
